<a href="https://colab.research.google.com/github/HerzelS/UNHCR-RMS-Analysis/blob/main/DRC%20RMS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# INTRODUCTION

This data pipeline is looking at data for the RBSA Livelihoods evaluation. However, the functions developed in this data pipeline can be reused in other evaluations and analytical work. A private github repository has been developed to house all the files used and can be made accessible to UNHCR Evaluation Office colleagues. The main focus of this data pipeline  is to:

* **Ensure the utilisation of reproducible data, making it easy to maintain institutional memory, share history with relevant colleagues and evaluation teams, document the thought process, update and correct errors**
* **Provide on one go; a pipeline that imports, cleans, wrangles, analyses and plots graphs all on one click within the R environment - no need to go to MS Excel or MS Word, everything is done on this document**
* **Reproducibility - this pipeline ensures that data is reproducible and can be run by other colleagues, just fork the Git Repository and run this document, no need to re-do the data preparation multiple times.**

More specific to the RBSA Livelihoods Evaluation, this data pipeline cleans and wrangles data from the following:

* 7 RMS Data - the data covers the period 2022-2023 and was extracted from RIDL.

The data pipeline does the following:

1. Extract, clean and wrangle the three datasets mentioned above.
2. Join the three datasets into one complete data frame.
4. Export different cleaned datasets (optional)


### Indicators under exploration

The main indicators for extranction are:

1. Indicator 13.1 Proportion of people with an account at a bank or other financial institution or with a mobile-money-service provider

2. Indicator 13.2 Proportion of people who self-report positive changes in their income compared to previous year

3. Indicator 13.3 Proportion of people (working age) who are unemployed

However, the extraction will also include several demographic data and other related outcome data that can be used to analyse the interaction between livelihood outcomes and other outcome areas tracked by the RMS surveys.

In [ ]:
pip install pyreadr

Collecting pyreadr
  Downloading pyreadr-0.5.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.3 kB)
Requirement already satisfied: pandas>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from pyreadr) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.0->pyreadr) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.0->pyreadr) (1.17.0)
Downloading pyreadr-0.5.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (776 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 776.2/776.2 kB 34.9 MB/s eta 0:00:00
Installing collected packages: pyreadr
Successfully installed pyreadr-0.5.4

In [ ]:
# Import packages
import pyreadr
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.preprocessing import OneHotEncoder

# Checking for Multicolinearity using VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Show all columns
pd.set_option('display.max_columns', None)

## Import and Clean Datasets

In [ ]:
drc = pyreadr.read_r("/content/drive/MyDrive/RMS/DRC.rds")
df = drc[None]

In [ ]:
df.index

RangeIndex(start=0, stop=63699, step=1)

In [ ]:
[col for col in df.columns]

['hhid',
 'indid',
 'country',
 'personid',
 'pop_groups',
 'province',
 'end_result',
 'hh02',
 'hh03',
 'hh04',
 'hh05',
 'hh06',
 'calcul1',
 'age',
 'agemonths',
 'agemd',
 'hh0',
 'hh07_month',
 'hh07',
 'hh07_months',
 'agecalculated',
 'hh08',
 'relation_r',
 'adult18',
 'women_b',
 'father_b',
 'childless2',
 'childless2name',
 'women',
 'father',
 'adult',
 'women_b_count',
 'begin_group_6cr6y8l5v_count',
 '_validation_status',
 'oldesthhm',
 'oldesthead',
 'householdhead',
 'ind_age_month',
 'ref01',
 'citizenship',
 'ref02',
 'citizenship2',
 'ref03',
 'ref04',
 'ref05',
 'countrybirth',
 'ref09',
 'ref10a',
 'ref10b',
 'ref11',
 'ref12',
 'ref12a',
 'ref12b',
 'ref13',
 'ref14',
 'ref15',
 'ref16',
 'ref16_other',
 'ref16a',
 'ref16a_other',
 'idp01',
 'cv',
 'idp01a',
 'idp02',
 'idp02a',
 'idp02b',
 'idp03',
 'idp04',
 'reg01',
 'reg01a',
 'reg01b',
 'reg01c',
 'reg01d',
 'reg01e',
 'reg01f',
 'reg01g',
 'reg02',
 'reg03',
 'reg04',
 'reg05',
 'reg05a',
 'reg05b',
 'reg05c',
 'reg05d',
 'reg05e',
 'reg05f',
 'reg06',
 'indiv_05less_name',
 'indiv_05less_age',
 'age_month',
 'ind_name',
 'mmr01',
 'mmr02',
 'mmr03',
 'mmr04',
 'n_dis01',
 'dis01a',
 'dis01',
 'dis02',
 'dis03',
 'dis04',
 'dis05',
 'dis06',
 'hacc01',
 'hacc02',
 'hacc02_other',
 'hacc03',
 'hacc04',
 'hacc04_other',
 'hacc02_1',
 'hacc02_2',
 'hacc02_3',
 'hacc02_4',
 'hacc02_5',
 'hacc02_96',
 'hacc04_1',
 'hacc04_2',
 'hacc04_3',
 'hacc04_4',
 'hacc04_5',
 'hacc04_6',
 'hacc04_7',
 'hacc04_8',
 'hacc04_9',
 'hacc04_10',
 'hacc04_96',
 'idp01_1',
 'idp01_2',
 'idp01_3',
 'idp01_4',
 'idp01_5',
 'idp01_6',
 'idp01_7',
 'idp01_98',
 'idp01_99',
 'edu01',
 'edu01a',
 'edu02',
 'edu03',
 'edu04',
 'edu04_other',
 'comm01',
 'comm02',
 'comm03',
 'comm04',
 'hh07_cat',
 'hh07_cat2',
 'disa1_234',
 'disa2_234',
 'disa3_234',
 'disa4_234',
 'disa5_234',
 'disa6_234',
 'disa1_34',
 'disa2_34',
 'disa3_34',
 'disa4_34',
 'disa5_34',
 'disa6_34',
 'dissum234',
 'dissum34',
 'disability1',
 'disability2',
 'disability3',
 'disability4',
 'disab',
 'weight_indiv',
 'pop_groups_indiv',
 'region_indiv',
 'female',
 'age_cat',
 'disability_wg_ss',
 '_index',
 '_parent_index',
 'start',
 'end',
 'start_t',
 'end_t',
 'time_ds',
 'time_dm',
 'interviewdate',
 'countryname',
 'territoire',
 'settlement',
 'geopoint',
 'nb',
 'enqueteur',
 'intro01a',
 'intro02_idps',
 'intro02_progres',
 'intro03',
 'consent_form',
 'intro04',
 'intro05',
 'intro05_other',
 'hh01',
 'notepart1',
 'relation_count',
 'status_1',
 'namechild2less',
 'nochild2less',
 'women_name_b_total',
 'women_name_b',
 'father_name_b',
 'women_name',
 'father_name',
 'adult_name',
 'woman1',
 'woman2',
 'woman3',
 'woman4',
 'woman5',
 'woman6',
 'fam_name1',
 'fam_name2',
 'fam_name3',
 'fam_name4',
 'fam_name5',
 'fam_name6',
 'fam_name7',
 'fam_name8',
 'fam_name9',
 'fam_name10',
 'fam_name11',
 'fam_name12',
 'fam_name13',
 'fam_name14',
 'fam_name15',
 'fam_name16',
 'fam_name17',
 'fam_name18',
 'fam_name19',
 'fam_name20',
 'age1',
 'age2',
 'age3',
 'age4',
 'age5',
 'age6',
 'age7',
 'age8',
 'age9',
 'age10',
 'age11',
 'age12',
 'age13',
 'age14',
 'age15',
 'age16',
 'age17',
 'age18',
 'age19',
 'age20',
 'sex1',
 'sex2',
 'sex3',
 'sex4',
 'sex5',
 'sex6',
 'sex7',
 'sex8',
 'sex9',
 'sex10',
 'sex11',
 'sex12',
 'sex13',
 'sex14',
 'sex15',
 'sex16',
 'sex17',
 'sex18',
 'sex19',
 'sex20',
 'notes2',
 'dwe01',
 'dwe01_other',
 'dwe02',
 'dwe02_other',
 'dwe03',
 'dwe03_other',
 'dwe04',
 'dwe04_other',
 'dwe05',
 'filter_camp_hh',
 'dwe06',
 'dwe06_other',
 'dwe07',
 'dwe07_other',
 'dwe08',
 'dwe09',
 'dwe10',
 'dwe10_other',
 'dwe11',
 'cook01',
 'cook02',
 'cook02_other',
 'cook03',
 'cook03_other',
 'light01',
 'light02',
 'light02b',
 'light03',
 'light03b',
 'dwa01',
 'dwa01_other',
 'source',
 'source2',
 'dwa02',
 'dwa02_other',
 'dwa03',
 'dwa03a',
 'dwa03b',
 'dwa04',
 'toi01',
 'toi01_other',
 'toi02',
 'toi03',
 'toi03_other',
 'toi04',
 'toi04_other',
 'toi05',
 'latestson',
 'bir01',
 'bir02',
 'bir03',
 'bir03_other',
 'bir04',
 'bir04_other',
 'hea01',
 'hea01_other',
 'hea02',
 'hea02_other',
 'hea03',
 'spf01',
 'spf01_op',
 'spf01a',
 'spf01b',
 'spf01c',
 'spf01d',
 'spf01e',
 'spf01f',
 'spf01g',
 'spf01h',
 'pov0a_note',
 'pov01',
 'pov01a',
 'pov01ac',
 'pov02',
 'pov02a',
 'pov02ac',
 'pov03',
 'pov03a',
 'pov03ac',
 'pov04',
 'pov04a',
 'pov04b',
 'pov04bc',
 'pov04b_cal',
 'pov0source_total',
 'pov0source_gtotal',
 'pov05_note',
 'pov05a',
 'pov06a',
 'pov07a',
 'pov06a1',
 'pov05b',
 'pov06b',
 'pov06b1',
 'pov07b',
 'pov05c',
 'pov06c',
 'pov06c1',
 'pov07c',
 'pov05d',
 'pov06d',
 'pov06d1',
 'pov07d',
 'pov05e',
 'pov06e',
 'pov06e1',
 'pov07e',
 'pov05f',
 'pov06f',
 'pov06f1',
 'pov07f',
 'pov05g',
 'pov06g',
 'pov06g1',
 'pov07g',
 'pov05h',
 'pov06h',
 'pov06h1',
 'pov07h',
 'pov05i',
 'pov06i',
 'pov06i1',
 'pov07i',
 'pov05j',
 'pov06j',
 'pov06j1',
 'pov07j',
 'pov05k',
 'pov06k',
 'pov06k1',
 'pov07k',
 'pov06_total',
 'pov06_gtotal',
 'exp_6months',
 'fuel',
 'fuel01',
 'water',
 'water01',
 'electricity',
 'electricity01',
 'communication',
 'communication01',
 'hygiene',
 'hygiene01',
 'alcohol',
 'alcohol01',
 'transport',
 'transport01',
 'health',
 'health01',
 'education',
 'education01',
 'clothing',
 'clothing01',
 'debtrepay',
 'debtrepay01',
 'celebration',
 'celebration01',
 'equipment',
 'equipment01',
 'savings',
 'savings01',
 'assistance',
 'assistance01',
 'rent',
 'rent01',
 'agriculture',
 'agriculture01',
 'crops',
 'crops01',
 'labor',
 'labor01',
 'animals',
 'animals01',
 'exp_total',
 'show_exp_total',
 'notes3',
 'listadult',
 'n_selected_adult18',
 'selected_adult18',
 'name_selectedadult18_age',
 'name_selectedadult18',
 'individual',
 'random_present',
 'unem01_orig',
 'unem02_orig',
 'unem03_orig',
 'unem04_orig',
 'unem05_orig',
 'unem06',
 'unem07',
 'unem08',
 'unem09_orig',
 'unem10_orig',
 'inc01',
 'bank01',
 'bank02',
 'bank03',
 'bank04',
 'bank05',
 'saf01',
 'gbv_vaw',
 'gbv01_note',
 'gbv01_001',
 'gbv01a_orig',
 'gbv01b_orig',
 'gbv01c_orig',
 'gbv01d_orig',
 'gbv_screen',
 'vaw01_note',
 'vaw01',
 'vaw01a_orig',
 'vaw01b_orig',
 'vaw01c_orig',
 'vaw01d_orig',
 'vaw01e_orig',
 'end_survey_001',
 'contact_number',
 'number_respondent',
 'name_respondent',
 'final_notes',
 'final_notes_entry',
 'geopoint_latitude',
 'geopoint_longitude',
 'geopoint_altitude',
 'geopoint_precision',
 's1_count',
 's2_count',
 'instanceid',
 'rootuuid',
 'instancename',
 'deprecatedid',
 'uuid',
 '__version__',
 '_xform_id_string',
 '_uuid',
 '_status',
 '_submission_time',
 '_submitted_by',
 'p2s3_count',
 'gps',
 'bir03_1',
 'bir03_2',
 'bir03_3',
 'bir03_4',
 'bir03_5',
 'bir03_6',
 'bir03_96',
 'bir03_98',
 'geopoint_wkt',
 'weight',
 'pop_groups_hh',
 'region',
 'hhsize_hh',
 'hhsize_cat',
 'gbv01a',
 'gbv01b',
 'gbv01c',
 'gbv01d',
 'outcome4_1',
 'vaw01a',
 'vaw01b',
 'vaw01c',
 'vaw01d',
 'vaw01e',
 'outcome4_2',
 'year',
 'impact2_3',
 'impact3_2a',
 'impact3_2b',
 'impact3_3',
 'outcome1_2',
 'outcome1_3',
 'outcome5_2',
 'outcome8_2',
 'crowding_index',
 'outcome9_1',
 'outcome9_2',
 'outcome10_1',
 'outcome10_2',
 'outcome12_1',
 'outcome12_2',
 'outcome13_1',
 'outcome13_2',
 'unem01',
 'unem02',
 'unem03',
 'unem04',
 'unem05',
 'unem09',
 'unem10',
 'outcome13_3',
 'outcome16_1',
 'outcome16_2',
 'healthcare',
 'impact2_2']

In [ ]:
df.head()

,hhid,indid,country,personid,pop_groups,province,end_result,hh02,hh03,hh04,hh05,hh06,calcul1,age,agemonths,agemd,hh0,hh07_month,hh07,hh07_months,agecalculated,hh08,relation_r,adult18,women_b,father_b,childless2,childless2name,women,father,adult,women_b_count,begin_group_6cr6y8l5v_count,_validation_status,oldesthhm,oldesthead,householdhead,ind_age_month,ref01,citizenship,ref02,citizenship2,ref03,ref04,ref05,countrybirth,ref09,ref10a,ref10b,ref11,ref12,ref12a,ref12b,ref13,ref14,ref15,ref16,ref16_other,ref16a,ref16a_other,idp01,cv,idp01a,idp02,idp02a,idp02b,idp03,idp04,reg01,reg01a,reg01b,reg01c,reg01d,reg01e,reg01f,reg01g,reg02,reg03,reg04,reg05,reg05a,reg05b,reg05c,reg05d,reg05e,reg05f,reg06,indiv_05less_name,indiv_05less_age,age_month,ind_name,mmr01,mmr02,mmr03,mmr04,n_dis01,dis01a,dis01,dis02,dis03,dis04,dis05,dis06,hacc01,hacc02,hacc02_other,hacc03,hacc04,hacc04_other,hacc02_1,hacc02_2,hacc02_3,hacc02_4,hacc02_5,hacc02_96,hacc04_1,hacc04_2,hacc04_3,hacc04_4,hacc04_5,hacc04_6,hacc04_7,hacc04_8,hacc04_9,hacc04_10,hacc04_96,idp01_1,idp01_2,idp01_3,idp01_4,idp01_5,idp01_6,idp01_7,idp01_98,idp01_99,edu01,edu01a,edu02,edu03,edu04,edu04_other,comm01,comm02,comm03,comm04,hh07_cat,hh07_cat2,disa1_234,disa2_234,disa3_234,disa4_234,disa5_234,disa6_234,disa1_34,disa2_34,disa3_34,disa4_34,disa5_34,disa6_34,dissum234,dissum34,disability1,disability2,disability3,disability4,disab,weight_indiv,pop_groups_indiv,region_indiv,female,age_cat,disability_wg_ss,_index,_parent_index,start,end,start_t,end_t,time_ds,time_dm,interviewdate,countryname,territoire,settlement,geopoint,nb,enqueteur,intro01a,intro02_idps,intro02_progres,intro03,consent_form,intro04,intro05,intro05_other,hh01,notepart1,relation_count,status_1,namechild2less,nochild2less,women_name_b_total,women_name_b,father_name_b,women_name,father_name,adult_name,woman1,woman2,woman3,woman4,woman5,woman6,fam_name1,fam_name2,fam_name3,fam_name4,fam_name5,fam_name6,fam_name7,fam_name8,fam_name9,fam_name10,fam_name11,fam_name12,fam_name13,fam_name14,fam_name15,fam_name16,fam_name17,fam_name18,fam_name19,fam_name20,age1,age2,age3,age4,age5,age6,age7,age8,age9,age10,age11,age12,age13,age14,age15,age16,age17,age18,age19,age20,sex1,sex2,sex3,sex4,sex5,sex6,sex7,sex8,sex9,sex10,sex11,sex12,sex13,sex14,sex15,sex16,sex17,sex18,sex19,sex20,notes2,dwe01,dwe01_other,dwe02,dwe02_other,dwe03,dwe03_other,dwe04,dwe04_other,dwe05,filter_camp_hh,dwe06,dwe06_other,dwe07,dwe07_other,dwe08,dwe09,dwe10,dwe10_other,dwe11,cook01,cook02,cook02_other,cook03,cook03_other,light01,light02,light02b,light03,light03b,dwa01,dwa01_other,source,source2,dwa02,dwa02_other,dwa03,dwa03a,dwa03b,dwa04,toi01,toi01_other,toi02,toi03,toi03_other,toi04,toi04_other,toi05,latestson,bir01,bir02,bir03,bir03_other,bir04,bir04_other,hea01,hea01_other,hea02,hea02_other,hea03,spf01,spf01_op,spf01a,spf01b,spf01c,spf01d,spf01e,spf01f,spf01g,spf01h,pov0a_note,pov01,pov01a,pov01ac,pov02,pov02a,pov02ac,pov03,pov03a,pov03ac,pov04,pov04a,pov04b,pov04bc,pov04b_cal,pov0source_total,pov0source_gtotal,pov05_note,pov05a,pov06a,pov07a,pov06a1,pov05b,pov06b,pov06b1,pov07b,pov05c,pov06c,pov06c1,pov07c,pov05d,pov06d,pov06d1,pov07d,pov05e,pov06e,pov06e1,pov07e,pov05f,pov06f,pov06f1,pov07f,pov05g,pov06g,pov06g1,pov07g,pov05h,pov06h,pov06h1,pov07h,pov05i,pov06i,pov06i1,pov07i,pov05j,pov06j,pov06j1,pov07j,pov05k,pov06k,pov06k1,pov07k,pov06_total,pov06_gtotal,exp_6months,fuel,fuel01,water,water01,electricity,electricity01,communication,communication01,hygiene,hygiene01,alcohol,alcohol01,transport,transport01,health,health01,education,education01,clothing,clothing01,debtrepay,debtrepay01,celebration,celebration01,equipment,equipment01,savings,savings01,assistance,assistance01,rent,rent01,agriculture,agriculture01,crops,crops01,labor,labor01,animals,animals01,exp_total,show_exp_total,notes3,listadult,n_selected_adult18,selected_adult18,name_selectedadult18_age,name_selectedadult18,individual,random_present,unem01_orig,unem02_orig,unem03_orig,unem04_orig,unem05_orig,unem06,unem07,unem08,unem09_orig,unem10_orig,inc01,bank01,bank02,bank03,bank04,bank05,saf01,gbv_vaw,gbv01_note,gbv01_001,gbv01a_orig,gbv01b_orig,gbv01c_orig,gbv01d_orig,gbv_screen,vaw01_note,vaw01,vaw01a_orig,vaw01b_orig,vaw01c_orig,vaw01d_orig,vaw01e_orig,end_survey_001,contact_number,number_respondent,name_respondent,final_notes,final_notes_entry,geopoint_latitude,geopoint_longitude,geopoint_altitude,geopoint_precision,s1_count,s2_count,instanceid,rootuuid,instancename,deprecatedid,uuid,__version__,_xform_id_string,_uuid,_status,_submission_time,_submitted_by,p2s3_count,gps,bir03_1,bir03_2,bir03_3,bir03_4,bir03_5,bir03_6,bir03_96,bir03_98,geopoint_wkt,weight,pop_groups_hh,region,hhsize_hh,hhsize_cat,gbv01a,gbv01b,gbv01c,gbv01d,outcome4_1,vaw01a,vaw01b,vaw01c,vaw01d,vaw01e,outcome4_2,year,impact2_3,impact3_2a,impact3_2b,impact3_3,outcome1_2,outcome1_3,outcome5_2,outcome8_2,crowding_index,outcome9_1,outcome9_2,outcome10_1,outcome10_2,outcome12_1,outcome12_2,outcome13_1,outcome13_2,unem01,unem02,unem03,unem04,unem05,unem09,unem10,outcome13_3,outcome16_1,outcome16_2,healthcare,impact2_2
0,27283788.0,1.0,"Congo, DR",1.0,1.0,9x,1.0,Seke Kamalandua,1,1.0,1.0,8/29/1995,2023-02-28T00:00:00.000+08:00,27,330,6,NA,NA,27.0,NA,NA,7,1.0,1,Seke Kamalandua,NA,0.0,NA,Seke Kamalandua,NA,Seke Kamalandua,1.0,2.0,NA,NA,1,1.0,NA,0,AGO,AGO,Angola,0,NA,AGO,Angola,1,6/29/1997,NA,0,NA,NA,NA,1,NA,6,8,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Seke Kamalandua,27,NA,NA,NA,NA,NaN,NA,NA,NA,1,1,1,1,1,1,1.0,1 2,NA,0.0,NaN,NA,1,1,0,0,0,0,NA,NA,NA,NA,NA,NA,NaN,NaN,NA,NA,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NA,NaN,NaN,NA,NA,NA,NA,NA,NA,18-59,18-60+,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.043912,Refugees and Asylum Seekers,13.0,1.0,Adults (18-59),0.0,13867.0,13867.0,2023-02-28T10:14:20.927+08:00,2023-02-28T16:41:39.135+08:00,36860,57666,20806,346.76666666666665,2/28/2023,RÃÂ©publique DÃÂ©mocratique du Congo,9F,9F4,-4.3515927 15.3232569 296.6454473813451 4.766,NA,822,Tayaya Pope Gabrielle,NA,966-13H00136,1.0,OK,1.0,NA,NA,2.0,NA,1.0,NA,",",0.0,2.0,Seke Kamalandua Maria Seke chimene,NA,Seke Kamalandua Maria Seke chimene,NA,Seke Kamalandua Maria Seke chimene,Seke,Kamalandua,Maria,Seke,chimene,NA,Seke Kamalandua,Maria Seke chimene,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,27,32,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,1.0,1,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,8.0,NA,8.0,NA,8.0,NA,10.0,NA,1.0,0.0,2.0,NA,2.0,NA,0.0,NaN,NaN,NA,2.0,1.0,4.0,NA,3.0,NA,1.0,6.0,NA,8.0,NA,1.0,NA,Robinet dans le logement,NA,NaN,NA,NaN,NA,NA,NA,2.0,NA,2.0,NaN,NA,1,NA,1.0,",",NaN,0.0,NaN,NA,NA,NA,2.0,NA,3,NA,20.0,NA,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NA,2,100000,100000,99,NA,0,NA,NA,0,NA,NA,NA,0,0,100000,NA,NA,7,11200,1,11200,1,600,600,1,0,NA,0,NA,5,8000,8000,1,0,NA,0,NA,4,9500,9500,1,7,6500,6500,1,7,7350,7350,1,7,4000,4000,1,7,7000,7000,1,1,6500,6500,1,60650,NA,NA,90000,90000,10000,10000,7000,7000,120000,120000,36000,36000,0,0,216000,216000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,479000,NA,NA,1 2,2.0,2,32,Maria Seke chimene,NA,NA,0,1,NA,NA,NA,NaN,3.0,NaN,NA,NA,98.0,0.0,0.0,NaN,1,1.0,2.0,NA,NA,NA,1.0,1.0,1.0,1.0,0.0,NA,NA,NA,NA,NA,NA,NA,NA,0,NA,fam_name1,1,NA,-4.3515927,15.3232569,296.6454473813451,4.766,2.0,2.0,uuid:7f5bcf82-efdd-48d3-b63b-9f478bbd5a71,NA,NA,NA,2149c34ea7f74b489443766ce4fc97c9,v9337TvCFRkg3KLDqMYft6,aEqzWCJcQwNBAyGDWxjKVL,7f5bcf82-efdd-48d3-b63b-9f478bbd5a71,submitted_via_web,2023-02-28T17:02:52,rms_enq,2.0,NA,NaN,NaN,NaN,NA,NA,NA,NA,NA,POINT (15.3232569 -4.3515927 296.6454473813451),0.043912,Refugees and Asylum Seekers,13.0,2.0,1-3 members,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,2.000000,0.0,1.0,NaN,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,0.0
1,27283788.0,2.0,"Congo, DR",2.0,1.0,9x,1.0,Maria Seke chimene,8,1.0,0.0,NA,2023-02-28T00:00:00.000+08:00,NA,NA,NA,NA,NA,32.0,NA,NA,7,0.0,2,Maria Seke chimene,NA,0.0,NA,Maria Seke chimene,NA,Maria Seke chimene,1.0,2.0,NA,1,NA,0.0,NA,0,AGO,AGO,Angola,0,NA,AGO,Angola,1,6/29/1996,NA,0,NA,NA,NA,1,NA,6,8,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maria Seke chimene,32,NA,NA,NA,NA,NaN,NA,NA,NA,1,1,1,1,1,1,1.0,1,NA,0.0,NaN,NA,1,0,0,0,0,0,NA,NA,NA,NA,NA,NA,NaN,NaN,NA,NA,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NA,NaN,NaN,NA,NA,NA,NA,NA,NA,18-59,18-60+,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.043912,Refugees and Asylum Seekers,13.0,1.0,Adults (18-59),0.0,13867.0,13867.0,2023-02-28T10:14:20.927+08:00,2023-02-28T16:41:39.135+08:00,36860,57666,20806,346.76666666666665,2/28/2023,RÃÂ©publique DÃÂ©mocratique du Congo,9F,9F4,-4.3515927 15.3232569 296.6454473813451 4.766,NA,822,Tayaya Pope Gabrielle,NA,966-13H00136,1.0,OK,1.0,NA,NA,2.0,NA,1.0,NA,",",0.0,2.0,Seke Kamalandua Maria Seke chimene,NA,Seke Kamalandua Maria Seke chimene,NA,Seke Kamalandua Maria Seke chimene,Seke,Kamalandua,Maria,Seke,chimene,NA,Seke Kamalandua,Maria Seke chimene,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,27,32,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,1.0,1,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,8.0,NA,8.0,NA,8.0,NA,10.0,NA,1.0,0.0,2.0,NA,2.0,NA,0.0,NaN,NaN,NA,2.0,1.0,4.0,NA,3.0,NA,1.0,6.0,NA,8.0,NA,1.0,NA,Robinet dans le logement,NA,NaN,NA,NaN,NA,NA,NA,2.0,NA,2.0,NaN,NA,1,NA,1.0,",",NaN,0.0,NaN,NA,NA,NA,2.0,NA,3,NA,20.0,NA,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NA,2,100000,100000,99,NA,0,NA,NA,0,NA,NA,NA,0,0,100000,NA,NA,7,11200,1,11200,1,600,600,1,0,NA,0,NA,5,8000,8000,1,0,NA,0,NA,4,9500,9500,1,7,6500,6500,1,7,7350,7350,1,7,4000,4000,1,7,7000,7000,1,1,6500,6500,1,60650,NA,NA,90000,90000,10000,10000,7000,7000,120000,120000,36000,36000,0,0,216000,216000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,479000,NA,NA,1 2,2.0,2,32,Maria Seke chimene,NA,NA,0,1,NA,NA,NA,NaN,3.0,NaN,NA,NA,98.0,0.0,0.0,NaN,1,1.0,2.0,NA,NA,NA,1.0,1.0,1.0,1.0,0.0,NA,NA,NA,NA,NA,NA,NA,NA,0,NA,fam_name1,1,NA,-4.3515927,15.3232569,296.6454473813451,4.766,2.0,2.0,uuid:7f5bcf82-efdd-48d3-b63b-9f478bbd5a71,NA,NA,NA,2149c34ea7f74b489443766ce4fc97c9,v9337TvCFRkg3KLDqMYft6,aEqzWCJcQwNBAyGDWxjKVL,7f5bcf82-efdd-48d3-b63b-9f478bbd5a71,submitted_via_web,2023-02-28T17:02:52,rms_enq,2.0,NA,NaN,NaN,NaN,NA,NA,NA,NA,NA,POINT (15.3232569 -4.3515927 296.6454473813451),0.043912,Refugees and Asylum Seekers,13.0,2.0,1-3 members,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,2.000000,0.0,1.0,NaN,NaN,1.0,0.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,0.0
2,27283793.0,3.0,"Congo, DR",1.0,4.0,9x,1.0,Mamie ilunga,1,1.0,1.0,8/21/1976,2023-02-28T00:00:00.000+08:00,46,558,6,NA,NA,46.0,NA,NA,7,1.0,1,Mamie ilunga,NA,0.0,NA,Mamie ilunga,NA,Mamie ilunga,1.0,2.0,NA,1,1,1.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mamie ilunga,46,NA,NA,NA,NA,NaN,NA,NA,NA,1,1,1,1,1,1,NaN,NA,NA,NaN,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NA,NA,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NA,NaN,NaN,NA,NA,NA,NA,NA,NA,18-59,18-60+,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,2.791774,Host Communities,13.0,1.0,Adults (18-59),0.0,13866.0,13866.0,2023-02-28T12:06:48.586+08:00,2023-02-28T12:35:18.223+08:00,43608,NA,NA,NA,2/28/2023,RÃÂ©publique DÃÂ©mocratique du Congo,9F,9F4,-4.3519767 15.3230567 327.26253283548795 4.1,NA,822,Tayaya Pope,30058336419,NA,1.0,OK,1.0,NA,NA,2.0,NA,1.0,NA,",",0.0,1.0,Mamie ilunga,Mardoche kabongo,Mamie ilunga,Mardoche kabongo,Mamie ilunga Mardoche kabongo,Mamie,ilunga,NA,NA,NA,NA,Mamie ilunga,Mardoche kabongo,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,46,21,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,1.0,2,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,2.0,NA,8.0,NA,8.0,NA,12.0,NA,1.0,0.0,NaN,NA,NaN,NA,1.0,4.0,NaN,NA,NaN,1.0,NaN,NA,12.0,NA,1.0,1.0,NA,2.0,NA,2.0,NA,Robinet dans la concession/jardin/parcelle,NA,NaN,NA,NaN,NA,NA,NA,NaN,NA,NaN,NaN,NA,NA,NA,NaN,",",NaN,0.0,NaN,NA,NA,NA,4.0,NA,3,NA,30.0,NA,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NA,12,1000000,1000000,99,NA,0,NA,NA,0,NA,NA,NA,0,0,1000000,NA,NA,7,26000,1,26000,1,2000,2000,1,2,6000,6000,1,4,12000,12000,1,1,500,500,1,5,6500,6500,1,7,5000,5000,1,1,500,500,1,7,3000,3000,1,7,600,600,1,1,5000,5000,1,67100,NA,NA,180000,180000,68000,68000,36000,36000,89000,89000,70000,70000,12000,12000,120000,120000,800000,800000,450000,450000,35000,35000,0,0,120000,120000,0,0,0,0,200000,200000,1000000,1000000,0,0,0,0,0,0,0,0,3180000,NA,NA,1 2,2.0,1,46,Mamie ilunga,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NaN,NA,NA,NaN,NaN,NaN,NaN,NA,NaN,1.0,NA,NA,NA,1.0,1.0,1.0,1.0,1.0,NA,NA,0,0,0,0,0,NA,1,0995424264,fam_name1,0,NA,-4.3519767,15.3230567,327.26253283548795,4.1,2.0,2.0,uuid:f9108d15-bab1-4c76-bc5b-e6a55dee01ed,NA,NA,NA,2149c34ea7f74b489443766ce4fc97c9,v9337TvCFRkg3KLDqMYft6,aEqzWCJcQwNBAyGDWxjKVL,f9108d15-bab1-4c76-bc5b-e6a55dee01ed,submitted_via_web,2023-02-28T17:02:54,rms_enq,2.0,-4.3519691 15.323066 332.70305587241427 3.616,NaN,NaN,NaN,NA,NA,NA,NA,NA,POINT (15.3230567 -4.3519767 327.26253283548795),2.791774,Host Communities,13.0,2.0,1-3 members,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2023.0,NaN,NaN,NaN,1.0,NaN,0.0,NaN,0.0,2.000000,0.0,1.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0
3,27283793.0,4.0,"Congo, DR",2.0,4.0,9x,1.0,Mardoche kabongo,3,2.0,1.0,4/7/2001,2023-02-28T00:00:00.000+08:00,21,262,10,NA,NA,21.0,NA,NA,NA,0.0,2,NA,Mardoche kabongo,0.0,NA,NA,Mardoche kabongo,Mardoche kabongo,0.0,2.0,NA,NA,NA,0.0,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mardoche kabongo,21,NA,NA,NA,NA,NaN,NA,NA,NA,1,1,1,1,1,1,NaN,NA,NA,NaN,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NA,NA,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,NaN,NA,NaN,NaN,NA,NA,NA,NA,NA,NA,18-59,18-60+,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,2.791774,Host Communities,13.0,0.0,Adults (18-59),0.0,13866.0,13866.0,2023-02-28T12:06:48.586+08:00,2023-02-28T12:35:18.223+08:00,43608,NA,NA,NA,2/28/2023,RÃÂ©publique DÃÂ©mocratique du Congo,9F,9F4,-4.3519767 15.3230567 327.26253283548795 4.1,NA,822,Tayaya Pope,30058336419,NA,1.0,OK,1.0,NA,NA,2.0,NA,1.0,NA,",",0.0,1.0,Mamie ilunga,Mardoche kabongo,Mamie ilunga,Mardoche kabongo,Mamie ilunga Mardoche kabongo,Mamie,ilunga,NA,NA,NA,NA,Mamie ilunga,Mardoche kabongo,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,46,21,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,1.0,2,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,2.0,NA,8.0,NA,8.0,NA,12.0,NA,1.0,0.0,NaN,NA,NaN,NA,1.0,4.0,NaN,NA,NaN,1.0,NaN,NA,12.0,NA,1.0,1.0,NA,2.0,NA,2.0,NA,Robinet dans la concession/jardin/parcelle,NA,NaN,NA,NaN,NA,NA,NA,NaN,NA,NaN,NaN,NA,NA,NA,NaN,",",NaN,0.0,NaN,NA,NA,NA,4.0,NA,3,NA,30.0,NA,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NA,12,1000000,1000000,99,NA,0,NA,NA,0,NA,NA,NA,0,0,1000000,NA,NA,7,26000,1,26000,1,2000,2000,1,2,6000,6000,1,4,12000,12000,1,1,500,500,1,5,6500,6500,1,7,5000,5000,1,1,500,500,1,7,3000,3000,1,7,600,600,1,1,5000,5000,1,67100,NA,NA,180000,180000,68000,68000,36000,36000,89000,89000,70000,70000,12000,12000,120000,120000,800000,800000,450000,450000,35000,35000,0,0,120000,120000,0,0,0,0,200000,200000,1000000,1000000,0,0,0,0,0,0,0,0,3180000,NA,NA,1 2,2.0,1,46,Mamie ilunga,NA,NA,NA,NA,NA,NA,NA,NaN,NaN,NaN,NA,NA,NaN,NaN,NaN,NaN,NA,NaN,1.0,NA,NA,NA,1.0,1.0,1.0,1.0,1.0,NA,NA,0,0,0,0,0,NA,1,0995424264,fam_name1,0,NA,-4.3519767,15.3230567,327.26253283548795,4.1,2.0,2.0,uuid:f9108d15-bab1-4c76-bc5b-e6a55dee01ed,NA,NA,NA,2149c34ea7f74b489443766ce4fc97c9,v9337TvCFRkg3KLDqMYft6,aEqzWCJcQwNBAyGDWxjKVL,f9108d15-bab1-4c76-bc5b-e6a55dee01ed,submitted_via_web,2023-02-28T17:02:54,rms_enq,2.0,-4.3519691 15.323066 332.70305587241427 3.616,NaN,NaN,NaN,NA,NA,NA,NA,NA,POINT (15.3230567 -4.3519767 327.26253283548795),2.791774,Host Communities,13.0,2.0,1-3 members,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2023.0,NaN,NaN,NaN,1.0,NaN,0.0,NaN,0.0,2.000000,0.0,1.0,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0
4,27283798.0,5.0,"Congo, DR",1.0,1.0,9x,1.0,ExaucÃÂ©e Kamba,1,1.0,1.0,11/23/2001,2023-02-28T00:00:00.000+08:00,21,255,3,NA,NA,21.0,NA,NA,7,1.0,1,ExaucÃÂ©e Kamba,NA,0.0,NA,ExaucÃÂ©e Kamba,NA,ExaucÃÂ©e Kamba,1.0,4.0,NA,1,1,1.0,NA,0,CAF,CAF,Centrafrique,0,NA,CAF,Centrafrique,1,8/13/2013,NA,0,NA,NA,NA,0,CAF,6,8,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ExaucÃÂ©e Kamba,21,NA,NA,NA,NA,NaN,NA,NA,NA,1,1,1,1,1,1,1.0,1,NA,0.0,NaN,NA,1,0,0,0,0,0,NA,NA,NA,NA,NA,NA,NaN,NaN,NA,NA,NaN,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0,NA,NaN,NaN,NA,NA,NA,NA,NA,NA,18-59,18-60+,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.043912,Refugees and Asylum Seekers,13.0,1.0,Adults (18-59),0.0,13865.0,13865.0,2023-02-28T12:56:38.847+08:00,2023-02-28T16:27:36.989+08:00,46598,54302,7704,128.4,2/28/2023,RÃÂ©publique DÃÂ©mocratique du Congo,9F,9F4,-4.3471891 15.3222595 297.18252129233105 4.85,NA,822,Tayaya Pope,NA,966-13H00136,1.0,OK,1.0,NA,NA,4.0,NA,1.0,NA,", , ,",0.0,3.0,ExaucÃÂ©e Kamba Gemima Gaombalet Excellence ...,NA,ExaucÃÂ©e Kamba Excellence Kamba,NA,ExaucÃÂ©e Kamba Excellence Kamba,ExaucÃÂ©e,Kamba,Gemima,Gaombalet,Excellence,Kamba,ExaucÃÂ©e Kamba,Gemima Gaombalet,Domi Muaku,Excellence Kamba,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,21,13,10,19,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,1.0,1,2,1,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,2.0,NA,8.0,NA,8.0,NA,12.0,NA,3.0,0.0,2.0,NA,2.0,NA,1.0,4.0,1.0,NA,99.0,1.0,2.0,NA,10.0,NA,1.0,1.0,NA,2.0,NA,2.0,NA,Robinet dans la concession/jardin/parcelle,NA,NaN,NA,NaN,NA,NA,NA,2.0,NA,2.0,NaN,NA,1,NA,0.0,",",NaN,0.0,NaN,NA,NA,NA,2.0,NA,3,NA,45.0,NA,NA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NA,9,400000,400000,99,NA,0,NA,NA,0,NA,NA,NA,0,0,400000,NA,NA,7,8500,1,8500,7,7000,7000,1,1,3900,3900,1,1,2500,2500,1,1,4500,4500,1,3,6500,6500,1,7,8500,8500,1,7,10000,10000,1,7,5000,5000,1,7,800,800,1,0,NA,0,NA,57200,NA,NA,360000,360000,60000,60000,36000,36000,200000,200000,180000,180000,12000,12000,180000,180000,100000,100000,140000,140000,300000,300000,100000,100000,1000000,1000000,0,0,0,0,0,0,280000,280000,0,0,0,0,0,0,0,0,2948000,NA,NA,1 4,2.0,4,19,Excellence Kamba,NA,NA,0,0,0,0,0,NaN,NaN,NaN,0,0,98.0,0.0,0.0,NaN,1,1.0,1.0,NA,NA,NA,1.0,1.0,1.0,1.0,0.0,NA,NA,NA,NA,NA,NA,NA,NA,1,0852341423,fam_name1,0,NA,-4.3471891,15.3222595,297.18252129233105,4.85,4.0,4.0,uuid:296e8b06-22d9-4e3f-9a18-4e60bb8c9310,NA,NA,NA,2149c34ea7f74b489443766ce4fc97c9,v9337TvCFRkg3KLDqMYft6,aEqzWCJcQwNBAyGDWxjKVL,296e8b06-22d9-4e3f-9a18-4e60bb8c9310,submitted_via_web,2023-02-28T17:02:55,rms_enq,4.0,NA,NaN,NaN,NaN,NA,NA,NA,NA,NA,POINT (15.3222595 -4.3471891 297.18252129233105),0.043912,Refugees and Asylum Seekers,13.0,4.0,4-6 members,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,1.0,0.0,0.0,1.0,NaN,1.0,NaN,1.0,1.333333,0.0,1.0,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
df_select = df[['country',
                     'hhsize_hh',
                     'hh03',
                     'hh04',
                     'age',
                     'hh08',
                     'pop_groups_hh',
                     'female',
                     'age_cat',
                     'gps',
                     'geopoint',
                     'ref10a',
                     'reg01a',
                     'reg01b',
                     'reg01c',
                     'reg01d',
                     'reg01e',
                     'reg01f',
                     'reg01g',
                     'disability_wg_ss',
                     'outcome4_1',
                     'outcome4_2',
                     'outcome8_2',
                     'outcome9_1',
                     'outcome9_2',
                     'outcome13_1',
                     'outcome13_2',
                     'outcome13_3',
                     'outcome16_1',
                     'outcome16_2']]

In [ ]:
df_select = df_select.rename(columns=({'hh03': 'relationship_household_head',
                                         'hhsize_hh': 'hhsize',
                                         'hh03': 'relation_to_hh',
                                         'hh04': 'hhh_sex',
                                         'hh08': 'hh_marital_status',
                                         'female': 'gender',
                                         'pop_groups_hh': 'pop_groups',
                                         'ref10a':'date_of_arrival',
                                         'reg01a':'passport',
                                         'reg01b':'birth_certificate',
                                         'reg01c':'civil_or_gvt_id',
                                         'reg01d':'residency_permit',
                                         'reg01e':'statelessness_documentation',
                                         'reg01f':'hd_card_family_book_marriage_certificate',
                                         'outcome4_1': 'Know where to access available GBV services',
                                        'outcome4_2': 'Reject violence against women',
                                        'outcome8_2': 'Primary reliance on clean (cooking) fuels and technology',
                                        'outcome9_1': 'Living in habitable and affordable housing',
                                        'outcome9_2': 'Have energy to ensure lighting',
                                        'outcome13_1': 'Have an account at a bank or other financial institution or with a mobile-money-service provider',
                                        'outcome13_2': 'Self-report positive changes in their income compared to previous year',
                                        'outcome13_3': 'Being of working age but unemployed',
                                        'outcome16_1': 'Have secure tenure rights to housing and/or land',
                                        'outcome16_2': 'Covered by national social protection systems',
                                         'reg01g':'social_security_card'}))

df_select['country'] = df_select['country'].replace({'Congo, DR': 'DRC'})

In [ ]:
df_select.head()

,country,hhsize,relation_to_hh,hhh_sex,age,hh_marital_status,pop_groups,gender,age_cat,gps,geopoint,date_of_arrival,passport,birth_certificate,civil_or_gvt_id,residency_permit,statelessness_documentation,hd_card_family_book_marriage_certificate,social_security_card,disability_wg_ss,Know where to access available GBV services,Reject violence against women,Primary reliance on clean (cooking) fuels and technology,Living in habitable and affordable housing,Have energy to ensure lighting,Have an account at a bank or other financial institution or with a mobile-money-service provider,Self-report positive changes in their income compared to previous year,Being of working age but unemployed,Have secure tenure rights to housing and/or land,Covered by national social protection systems
0,DRC,2.0,1,1.0,27,7,Refugees and Asylum Seekers,1.0,Adults (18-59),NA,-4.3515927 15.3232569 296.6454473813451 4.766,6/29/1997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
1,DRC,2.0,8,1.0,NA,7,Refugees and Asylum Seekers,1.0,Adults (18-59),NA,-4.3515927 15.3232569 296.6454473813451 4.766,6/29/1996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
2,DRC,2.0,1,1.0,46,7,Host Communities,1.0,Adults (18-59),-4.3519691 15.323066 332.70305587241427 3.616,-4.3519767 15.3230567 327.26253283548795 4.1,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0
3,DRC,2.0,3,2.0,21,NA,Host Communities,0.0,Adults (18-59),-4.3519691 15.323066 332.70305587241427 3.616,-4.3519767 15.3230567 327.26253283548795 4.1,NA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,0.0,0.0,1.0,NaN,NaN,0.0,0.0,0.0
4,DRC,4.0,1,1.0,21,7,Refugees and Asylum Seekers,1.0,Adults (18-59),NA,-4.3471891 15.3222595 297.18252129233105 4.85,8/13/2013,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,NaN,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0